# Generated by Django 5.2.4 on 2025-08-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOsblog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
